services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql:Z
    ports:
      - 3306:3306

volumes:
  mariadb_data:
    name: mariadb_data